### ISSUE TITLE
Release 1.22

### ISSUE THREAD

**Issue by Krinkle** [countervandalism/CVNBot#50]
* [x] Promote master branch to `1.22.0-beta.1` (this allows us to distinguish with `BotName version` on IRC from `1.22.0-alpha`).
* [x] Upgrade 1 CVNBot to the latest version.
   https://github.com/countervandalism/infrastructure/blob/master/tasks.yaml#L98
* [x] Slowly upgrade the other CVNBot instances on cvn-app servers to the latest version.
* [x] In case of any issues, fix the bugs, increase beta version, and start again.
* [x] Once applied to all instances without issues for a week, update change log, and bump master branch to `1.22.0` (stable).
* [x] Create tag `v1.22.0` tag in git.
* [x] Bump master branch to `3.0.0-alpha`.

### Deployment for 1.22.0-beta.1

* [x] CVNBot18 (cvn-app8)

### Deployment for 1.22.0-beta.2

* cvn-app8
  * [x] Cubbie
  * [x] CVNBot1
  * [x] CVNBot2
  * [x] CVNBot3
  * [x] CVNBot4
  * [x] CVNBot5
  * [x] CVNBot18

### Deployment for 1.22.0-beta.3

* cvn-app8
  * [x] Cubbie
  * [x] CVNBot1
  * [x] CVNBot2
  * [x] CVNBot3
  * [x] CVNBot4
  * [x] CVNBot5
  * [x] CVNBot12
  * [x] CVNBot13
  * [x] CVNBot14
  * [x] CVNBot18
  * [x] CVNBot20
  * [x] CVNBot21
  * [x]  SWBot3
* cvn-app9
  * [x] CVNBot6
  * [x] CVNBot7
  * [x] CVNBot8
  * [x] CVNBot9
  * [x] CVNBot10
  * [x] CVNBot16
  * [x] CVNBot17
  * [x] CVNBot19
  * [x] CVNBot22
  * [x] CVNBot23
  * [x] CVNBot24
  * [x] CVNBot25
  * [x] CVNBot26
  * [x] CVNBot27
  * [x] CVNBot28
  * [x] CVNBot29

**Comment by Krinkle** [comment]
I've upgraded CVNBot18  to `1.22.0-beta.1` (feeds cvn-wikidata, runs on cvn-app8).

**Comment by Krinkle** [comment]
I've tagged the next beta and upgraded CVNBot18, Cubbie, CVNBot1-5 to `1.22.0-beta.2` (all on cvn-app8).

**Comment by Krinkle** [comment]
Cubbie is crashing on start up:

```
Jul 21 19:56:02 cvn-app8 CVNBot.exe[8647]:

ERROR [Main] CVNBot.Program [Cubbie]

Caught unhandled exception in global catcher#012System.Collections.Generic.KeyNotFoundException:
  The given key 'reblockRegex' was not present in the dictionary.

  #012  at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) <0x7f70ef7c83c0 + 0x00074> in <3833a6edf2074b959d3dab898627f0ac>:0
  #012  at CVNBot.Project.GenerateRegexen () [0x0014f] in <0ed46a4f75d24dd5b8e72cf04d480d64>:0
  #012  at CVNBot.Project.ReadProjectDetails (System.String xml) [0x00475] in <0ed46a4f75d24dd5b8e72cf04d480d64>:0
  #012  at CVNBot.ProjectList.LoadFromFile () [0x0005d] in <0ed46a4f75d24dd5b8e72cf04d480d64>:0
  #012  at CVNBot.Program.Main () [0x006d6] in <0ed46a4f75d24dd5b8e72cf04d480d64>:0

```

**Comment by Krinkle** [comment]
I've fixed the regression in https://github.com/countervandalism/CVNBot/commit/48e03f1959, tagged release 1.22.0-beta.3 , and re-started the upgrade plan (see comment 0).

**Comment by Krinkle** [comment]
The upgrade to beta.3 happen on July 21st. Here's some monitoring graphs for the 3 days since then, compared to past week, month and year.

### CPU

<img width="748" alt="Graph of cpu from cvn-app8 by week, month, and year" src="https://user-images.githubusercontent.com/156867/61823274-64e8ae80-ae53-11e9-89c6-8d4afdf8d253.png">

### Load Average
<img width="765" alt="Graph of load average from cvn-app8 by week, month, and year" src="https://user-images.githubusercontent.com/156867/61823329-85186d80-ae53-11e9-8773-432582b10e82.png">
age

### Memory

<img width="753" alt="Graph of memory usage from cvn-app8 by week, month, and year" src="https://user-images.githubusercontent.com/156867/61823433-bdb84700-ae53-11e9-9f77-a0497c9960a8.png">

**Comment by Krinkle** [comment]
This all looks good to me, so I'm gonna continue with the upgrades.
